### ISSUE TITLE
VCC 3.5.0 with QvPen 3.2.10 vpm and Unity 2022 is errors?

### ISSUE THREAD

**Issue by ChristianNar** [ureishi/QvPen#22]
![Unity_LI4MJNYjVD](https://github.com/ureishi/QvPen/assets/40973416/e08fb1c3-e869-4614-a2b4-b1be499fcb33)
![Unity_gpq27mJxiA](https://github.com/ureishi/QvPen/assets/40973416/ddd3744b-9c95-4c2a-98a7-a7a9c34417d1)

- Installed QvPen (v3.2.10~3.2.9) for VPM to VCC (v3.5.0) have Unity 2022 is errors...
- I remove QvPen for VPM already and I test try QvPen (v3.2.9) UnityPackage is yes working.

**Comment by anatawa12** [comment]
It was already error in 2019 and I just made pull request to fix that: #23
